In [22]:
import pandas as pd 

path = r"C:\Users\mail2\Documents\lpth\.vscode\DataSciencePrac\projects\BackendProjects\project4\app\searchapp\static\searchapp\restaurants_small.csv"
df = pd.read_csv(path)

df

,id,name,location,items,lat_long,full_details
0,11116,Udupi Thaja Thindi,BTM,"{""2 Idli with 1 Vada"": ""60.00 "", ""Masala Dosa""...","12.9152311463,77.6001443714","{""name"": ""Udupi Thaja Thindi"", ""offers"": [], ""..."
1,9851,Momo Hut,Koramangala 5th Block,"{""Steamed Veg Momos"": ""90.00 "", ""Steamed Chick...","12.9341887415,77.6157491282","{""name"": ""Momo Hut"", ""offers"": [], ""cuisines"":..."
2,8380,Chandrika Tiffins,Whitefield,"{""Aloo Paratha"": ""35.00 "", ""Gobi Paratha"": ""40...","13.0157964869,77.7620874345","{""name"": ""Chandrika Tiffins"", ""offers"": [], ""c..."
3,8462,Shuchi Ruchi,Malleshwaram,"{""Gobi Manchurian"": ""90.00 "", ""Paneer Manchuri...","13.0011596277,77.5723362342","{""name"": ""Shuchi Ruchi"", ""offers"": [], ""cuisin..."
4,8466,Smiley's Kitchen,Koramangala 1st Block,"{""Egg Bhurji"": ""60.00 "", ""Aloo Paratha"": ""40.0...","12.9295714466,77.6324777305","{""name"": ""Smiley's Kitchen"", ""offers"": [], ""cu..."
...,...,...,...,...,...,...
495,8087,hwealthcafe,HSR,"{""Spicy Chickpea Burger"": ""185.00 "", ""Spicy Co...","12.9172017079,77.6513631642","{""name"": ""hwealthcafe"", ""offers"": [], ""cuisine..."
496,10038,Sree Food Paradise,BTM,"{""Masala Dosa"": ""60.00 "", ""Gobi Manchurian"": ""...","12.9154990000,77.6130900000","{""name"": ""Sree Food Paradise"", ""offers"": [], ""..."
497,9553,Gurukrupa Paratha House,Domlur,"{""Veg Paratha Combo"": ""85.00 "", ""Non- Veg Para...","12.9603109555,77.6382213458","{""name"": ""Gurukrupa Paratha House"", ""offers"": ..."
498,9980,Hotel Shreekshetra,Sarjapur Road,"{""Kadhai Chicken"": ""180.00 "", ""Veg Noodles"": ""...","12.9134213532,77.6787186787","{""name"": ""Hotel Shreekshetra"", ""offers"": [], ""..."
499,11042,Behrouz Biryani,"ITPL Main Road, Whitefield","{""Murgh Queema Kefta Biryani & Ayran Combo"": ""...","12.9654350000,77.7178990000","{""name"": ""Behrouz Biryani"", ""offers"": [], ""cui..."

In [54]:
print(len(items_set))

25206